# _config.yml 예시
title: Kuax Blog
author: Jayden
description: >-
  놀기 좋아하는 개발자의 블로그
baseurl: ""
url: "https://blog.kuax.org" # 실제 서비스될 블로그 주소
timezone: Asia/Seoul
asset-url: /assets
livereload: true
collections:
  posts:
    output: true
    permalink: /:title